### ISSUE TITLE
Trigger fan out should propagate the data invalid flag from the trigger

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/ApplicationCore#109]
If a trigger comes with a data invalid flag, the fan-out will trigger. It should then propagate the data invalid flag to the outputs.

**Comment by killenb** [comment]
Once this is implemented, activate the test "testInvalidTrigger" in the file testPropagateDataFaultFlag.cc".

**Comment by killenb** [comment]
Thinking about it, I don't know if this even makes sense. There are two way you can argue:
* Conceptually the trigger is void. So it's pure arrival makes it valid. What is the data validity of void?
=> If you reason like this, this whole ticket does not make sense.
* You might use some data coming from another server as trigger. If this one tells you that the data is faulty, so does it make sense to also flag the data which was triggered by it as faulty?

**Comment by mhier** [comment]
Remember we also set the invalid flag if devices are not available. Hence if another server is supposed to deliver a trigger but currently the connection is broken, we should mark all variables which normally are triggered as faulty, because they won't be updated. So yes, it makes perfectly sense.
If you want to talk about the concept: the trigger payload data may be conceptually void, but it sill carries timing information. This information is not valid any more, so we have to mark this.

**Comment by mhier** [comment]
This is already implemented.
