### ISSUE TITLE
Race condition on shutdown

### ISSUE THREAD

**Issue by phako** [ChimeraTK/ApplicationCore#119]
If a device is in error state when shutting down the server, there is a race condition between unlocking the errorIsResolvedCondVar and hitting the boost::interruption_point here https://github.com/ChimeraTK/ApplicationCore/blob/master/src/DeviceModule.cc#L255

Since the deviceHasError never becomes true, we can hit the condition variable right again and it will never be triggered.

A quick solution could be the use of boost::condition_variable which supports interruption_points itself

**Comment by phako** [comment]
Actually,I think if we are using boost::thread we should probably be using boost thread primitives anyway

**Comment by mhier** [comment]
Not sure if this one is still happening. Needs careful investigation. Close if it cannot be reproduced, try to fix otherwise.

**Comment by mhier** [comment]
The code in question is no longer existent. Also there is no condition variable at all in the DeviceModule left. All mutexes are boost mutexes. Hence I think we should be fine.

To be sure I will test shutting down the llrfctrl server a few times while the x2timer server was stopped and the error was reported (x2timer_server was running at each start of the llrfctrl server). This will take a while, since I have to wait for the 4 minute timeout on each attempt...

**Comment by mhier** [comment]
I did not see this issue any more.
