### ISSUE TITLE
Circular dependencies cause infite data invalid loop

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/ApplicationCore#203]
If two (or more) modules have a circular dependency, the current implementation causes the an data invalid flag to be propagated in a loop and never disappear.

A workaround is to avoid circular dependencies, but this is in general not always possible.

Task:
* Find a solution to avoid the circular propagation of the invalid flag

Possible approach:
* A circular dependency only works if at least one of the inputs is poll-type. This asymmetry might be used in the circular dependency detector to turn off the flag propagation

**Comment by mhier** [comment]
I think the cleanest way to solve this is to trace back were the invalid flags are coming from. We basically need to make sure that we never give back the flag to the module were it came from. This is not easy to implement though.

Basically each module (incl. fan outs, excl. device and control system modules) needs to maintain a list of modules (same definition) from which it has received invalid data. When passing on the data invalid flag, the list is recursively iterated, and the flag is only passed on to the particular variable, if the receiver has not been found in those lists. Recursing the lists needs to be implemented carefully, since there might be dependency circles of other modules, and we do not want infinitive recursion.

This is implementable without changing the ProcessArray / TransferElement classes, because we have full access to the variable model. We only need to know the direct neighbours - we can collect this information in the startup phase and cache it in each module (because our model is at least currently quite inefficient and cannot answer these questions enough at runtime fast).

**Comment by mhier** [comment]
This issue is now tracked in redmine (sorry DESY-internal link):
https://redmine.msktools.desy.de/issues/7834

**Comment by mhier** [comment]
done
